name: tingere
version: 1.7.0
main: org.icarus.tingere.Tingere
api-version: "1.21"
authors: ["Annieawa", "Ph0sphorW"]
description: The data-driven, DataComponent friendly custom recipe plugin

commands:
  tingere:
    description: 重载自定义配方，获取配方结果/原料，或为玩家解锁配方
    usage: /tingere reload | /tingere get result <key> [amount] | /tingere get ingredient <key> [index] | /tingere get recipes <player> <pattern>
    aliases: [ tg, trecipes ]
    permission: tingere.admin

permissions:
  tingere.admin:
    description: 允许使用所有插件命令
    default: op