name: tingere
version: 1.6.4-BETA
main: org.icarus.tingere.Tingere
api-version: "1.21"
author: [AnnieWa, Ph0sphorW]
description: 支持物品组件的自定义配方插件

commands:
  tingere:
    description: 重载自定义配方，获取配方结果/原料，或为玩家解锁配方
    usage: /tingere reload | /tingere get result <key> [amount] | /tingere get ingredient <key> [index] | /tingere get recipes <player> <pattern>
    aliases: [ tg, trecipes ]
    permission: tingere.admin

permissions:
  tingere.admin:
    description: 允许使用所有插件命令
    default: op