name: tingere
version: 1.9.0
main: org.icarus.tingere.Tingere
api-version: "1.21"
authors: ["Annieawa", "Ph0sphorW"]
description: The data-driven, DataComponent friendly custom recipe plugin

permissions:
  tingere.admin:
    description: 允许使用所有插件命令
    default: op